AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Check Fraud API written with SpringBoot3 and Java 21 with the aws-serverless-java-container library

Globals:
  Function:
    Timeout: 30

Resources:
  UserCheckFraudFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: co.rooam.user.fraud.checker.LambdaHandler::handleRequest
      Runtime: java21 # compile JDK 21 corretto
      Architectures:
        - x86_64
      MemorySize: 2048 # 2GB is suggested for a Java lambda
      SnapStart: # SnapStart to improve cold start
        ApplyOn: "PublishedVersions"
      AutoPublishAlias: "prod"
      Timeout: 60
      Events:
        UserCheckFraud:
          Type: Api # https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  UserCheckFraudApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod' # Default stage is Prod
    Export:
      Name: UserCheckFraudApi
  UserCheckFraudFunction:
    Description: Lambda Function ARN
    Value: !GetAtt UserCheckFraudFunction.Arn
    Export:
      Name: UserCheckFraudFunction